version: 2.0.1.{build}
image: Previous Visual Studio 2017
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
install:
- cmd: dotnet restore
build:
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: HWgCHg1iktcPj5Rj3vHVl8MxLOeCSeuD26RbVBZZ5JWq+ufsOLBradErx4HLoj6n
  on:
    branch: master